### ISSUE TITLE
clientAccessToken cannot be empty

### ISSUE THREAD

**Issue by bimalkumarh** [dialogflow/dialogflow-nodejs-client#104]
I am getting the below error when running the application

node_modules\apiai\module\apiai.js:73
throw new Error('\'clientAccessToken\' cannot be empty.');

I have commented the below code block in apiai.js and it is now working fine.

/* if (!clientAccessToken) {
      throw new Error('\'clientAccessToken\' cannot be empty.');
}?*/

Any workaround for this?

**Comment by nvtuan305** [comment]
Why do you want to create a new apiai with empty access token?

**Comment by pranavvardia** [comment]
I have set the client access token in app.json but still I am getting this exception

**Comment by jordanvape** [comment]
i need to fix this problem please guys 

Error: 'clientAccessToken' cannot be empty.
    at createApplicationNew (C:\Users\Mutaz Maiitah\Desktop\discord-ai-bot\node_modules\apiai\module\apiai.js:73:15)
    at createApplication (C:\Users\Mutaz Maiitah\Desktop\discord-ai-bot\node_modules\apiai\module\apiai.js:96:37)
    at Object.<anonymous> (C:\Users\Mutaz Maiitah\Desktop\discord-ai-bot\main.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
PS C:\Users\Mutaz Maiitah\Desktop\discord-ai-bot>
